// <auto-generated/>
using System;
using System.Windows;
using Core.Config;

namespace UI
{
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            try
            {
                // Touch the config store so %ProgramData%\ATVCompanion exists early.
                var cfg = ConfigStore.Load();
                if (cfg == null)
                {
                    ConfigStore.Save(new AppConfig());
                }
            }
            catch (Exception)
            {
                // Non-fatal for UI startup.
            }
        }
    }
}